### ISSUE TITLE
Node version issues

### ISSUE THREAD

**Issue by cdoremus** [blacksonic/angular2-es6-starter#5]
Hi,

I cloned this repo, installed the node modules (npm install), 'gulp serve' and this is what happened:
```
craig@craig-G750JX:~/git/angular2-es6-starter$ gulp serve
/home/craig/git/angular2-es6-starter/gulpfile.js:2
let gulp = require('gulp');
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/lib/node_modules/gulp/node_modules/liftoff/index.js:181:16)
    at module.exports (/usr/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
```
This is the node and npm versions I was running at the `time:`
```
craig@craig-G750JX:~/git/angular2-es6-starter$ node -v
v0.12.7
craig@craig-G750JX:~/git/angular2-es6-starter$ npm -v
3.7.5
```
I upgraded node to 5.7.1 and npm to 3.8.0 and 'gulp serve' worked as expected. You might want to put something in the Readme about this.

**Comment by blacksonic** [comment]
What is present in the ```package.json``` file will put it also into the readme.

**Comment by blacksonic** [comment]
Added Node version info in latest commit https://github.com/blacksonic/angular2-es6-starter/commit/f5aa700c68a30c27f517e05579ed385b4b36e0ea
